### ISSUE TITLE
win11环境下构建electorn环境失败

### ISSUE THREAD

**Issue by kawaiior** [akirarika/milkio#21]
已经全局安装了 ts-node 和 typescript 但是构建环境时依然提示`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for E:\project\milk\test\milkio-project\node_modules\milkio\c.ts`

构建时的信息如下：
```
E:\project\milk\test>bun create milkio
√ 🥛 Hello! What language do you want to read? · 中文
√ 🥛 你更喜欢哪个运行时？ · electron (beta)
√ 🥛 你的工程叫什么名字？ · milkio-project
√ 🥛 你更喜欢哪个镜像源？(推荐中国大陆用户使用非默认的镜像源哦) · https://mirrors.cloud.tencent.com/npm/
\ 🥛 Milkio Creating..

bun install v1.1.17 (bb66bba1)
[31.00ms] migrated lockfile from package-lock.json

+ @biomejs/biome@1.8.0
+ @electron-forge/cli@7.4.0
+ @electron-forge/maker-deb@7.4.0
+ @electron-forge/maker-rpm@7.4.0
+ @electron-forge/maker-squirrel@7.4.0
+ @electron-forge/maker-zip@7.4.0
+ @electron-forge/plugin-auto-unpack-natives@7.4.0
+ @electron-forge/plugin-fuses@7.4.0
+ @electron/fuses@1.8.0
+ @types/node@20.14.2
+ electron@30.0.9
+ typescript@5.4.5
+ vite-node@1.6.0
+ @hattip/adapter-node@0.0.45
+ astro@4.9.3
+ client@packages/client
+ detect-port@1.6.1
+ electron-squirrel-startup@1.0.1
+ milkio@0.5.2 (v0.6.0 available)
+ milkio-static-for-node@0.0.3
+ milkio-template@0.0.2
+ typia@6.0.6
+ unplugin-auto-import@0.17.6

917 packages installed [11.80s]

Blocked 1 postinstall. Run `bun pm untrusted` for details.
Removed: 2
bun add v1.1.17 (bb66bba1)

+ client@packages/client

installed milkio@0.6.0 with binaries:
 - milkio
installed milkio-template@0.0.2

5 packages installed [7.08s]
$ node node_modules/milkio/c.ts gen
node:internal/modules/esm/get_format:160
  throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
        ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for E:\project\milk\test\milkio-project\node_modules\milkio\c.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:396:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:45)
    at async link (node:internal/modules/esm/module_job:78:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v20.15.0
error: script "milkio" exited with code 1
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: bun run milkio gen
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at createMilkio (file:///C:/Users/34886/AppData/Local/Temp/bunx-771214610-create-milkio@latest/node_modules/create-milkio/index.mjs:186:2)
    at async file:///C:/Users/34886/AppData/Local/Temp/bunx-771214610-create-milkio@latest/node_modules/create-milkio/index.mjs:249:1 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8272,
  stdout: null,
  stderr: null
}

Node.js v20.15.0

E:\project\milk\test>
```

**Comment by akirarika** [comment]
可以尝试一下，运行 `bun create milkio@0.1.34` 是否会有效捏

**Comment by kawaiior** [comment]
> 可以尝试一下，运行 `bun create milkio@0.1.34` 是否会有效捏

还是会报一样的错误。但是项目是可以创建出来的。而且在创建出来的项目里，删掉`node_modules`文件夹后，运行`co i`与milkio插件里的Generate就可以正常使用了。

**Comment by kawaiior** [comment]
> `bun create milkio@0.1.37` 这个版本应该修复啦，试试看

收到，我这就去试试，辛苦啦

**Comment by kawaiior** [comment]
> `bun create milkio@0.1.37` 这个版本应该修复啦，试试看

现在有了新的问题。命令行提示`c.ts`没有找到。`Script not found "node_modules/milkio/c.ts"`
```
E:\project\milk\test>bun create milkio@0.1.37
√ 🥛 Hello! What language do you want to read? · 中文
√ 🥛 你更喜欢哪个运行时？ · electron (beta)
√ 🥛 你的工程叫什么名字？ · milkio-project-test
√ 🥛 你更喜欢哪个镜像源？(推荐中国大陆用户使用非默认的镜像源哦) · https://mirrors.cloud.tencent.com/npm/
| 🥛 Milkio Creating..

bun install v1.1.17 (bb66bba1)
[27.09ms] migrated lockfile from package-lock.json

+ @biomejs/biome@1.8.0
+ @electron-forge/cli@7.4.0
+ @electron-forge/maker-deb@7.4.0
+ @electron-forge/maker-rpm@7.4.0
+ @electron-forge/maker-squirrel@7.4.0
+ @electron-forge/maker-zip@7.4.0
+ @electron-forge/plugin-auto-unpack-natives@7.4.0
+ @electron-forge/plugin-fuses@7.4.0
+ @electron/fuses@1.8.0
+ @types/node@20.14.2
+ electron@30.0.9
+ typescript@5.5.2
+ vite-node@1.6.0
+ @hattip/adapter-node@0.0.45
+ astro@4.9.3
+ client@packages/client
+ detect-port@1.6.1
+ electron-squirrel-startup@1.0.1
+ milkio@0.7.0-alpha.1
+ milkio-static-for-node@0.0.3
+ milkio-template@0.0.2
+ typia@6.0.6
+ unplugin-auto-import@0.17.6

917 packages installed [13.11s]

Blocked 1 postinstall. Run `bun pm untrusted` for details.
Removed: 2
bun add v1.1.17 (bb66bba1)

+ client@packages/client

installed milkio@0.7.0-alpha.1 with binaries:
 - milkio
installed milkio-template@0.0.2

2 packages installed [8.19s]
$ bun run node_modules/milkio/c.ts gen
error: Script not found "node_modules/milkio/c.ts"
error: script "milkio" exited with code 1
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: powershell.exe -command bun run milkio gen
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at createMilkio (file:///C:/Users/34886/AppData/Local/Temp/bunx-771214610-create-milkio@0.1.37/node_modules/create-milkio/index.mjs:194:3)
    at async file:///C:/Users/34886/AppData/Local/Temp/bunx-771214610-create-milkio@0.1.37/node_modules/create-milkio/index.mjs:258:1 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20804,
  stdout: null,
  stderr: null
}

Node.js v20.15.0

E:\project\milk\test>
```

**Comment by akirarika** [comment]
Windows 设备上使用 powershell 可以运行 `bun run node_modules/milkio/c.ts gen` 这个命令嘛

**Comment by kawaiior** [comment]
> bun run node_modules/milkio/c.ts gen
无法运行，命令行提示脚本未找到。
`PS E:\project\milk\test> bun run node_modules/milkio/c.ts gen`
`error: Script not found "node_modules/milkio/c.ts"`
`PS E:\project\milk\test> bun run .\milkio-project-test\node_modules\milkio\c.ts gen`
`error: Script not found ".\milkio-project-test\node_modules\milkio\c.ts"`

**Comment by akirarika** [comment]
晚上我看一下好啦
